name: My Test Pipeline

on: [push] # The trigger [2]

jobs:
  build:
    runs-on: ubuntu-latest # The free virtual machine [5]
    steps:
      - name: 1. Check out code
        uses: actions/checkout@v3

      - name: 2. Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: pip install -r requirements.txt [3]

      - name: 4. Run tests
        run: pytest [3, 4]

